# -*- coding: utf-8 -*-
"""pose_distance.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zSdj80fFJkwrwQ6Vxix36b1XPT9MYBQ
"""

import sys
import math
import cv2
import jetson_inference
import jetson_utils

# SETTINGS & RULES
# We consider any two people closer than this pixel distance a violation.
DISTANCE_THRESHOLD_PX = 300

# Camera hardware settings. Using 640x480 is the "sweet spot" for Jetson Nano performance.
CAMERA_INDEX          = 0
FRAME_WIDTH           = 640
FRAME_HEIGHT          = 480
FRAME_FPS             = 30

# Defining our visual palette for the HUD and alerts.
GREEN  = (0,   255, 0)   # Safe status
RED    = (0,   0,   255)   # Danger/Violation status
WHITE  = (255, 255, 255)
BLACK  = (0,   0,    black)
YELLOW = (0,   255, 255) # For distance labels

# BRAINS OF THE OPERATION
def get_hip_center(pose):
    """
    To measure distance, we need a single point for each person.
    We prefer the midpoint of the hips, but we have a fallback list
    (shoulders, neck, nose) in case the camera can't see the full body.
    """
    LEFT_HIP  = 11
    RIGHT_HIP = 12

    # Our priority list: if hips aren't found, try shoulders, then neck, then nose.
    PRIORITY = [11, 12, 5, 6, 17, 0]
    found = {}

    for kp in pose.Keypoints:
        if kp.ID in PRIORITY:
            found[kp.ID] = kp

    # Step 1: Try to find the perfect center between the hips [cite: 24]
    if 11 in found and 12 in found:
        return ((found[11].x + found[12].x) / 2.0,
                (found[11].y + found[12].y) / 2.0)

    # Step 2: Fallback to just one visible hip
    for fid in [11, 12]:
        if fid in found:
            return (found[fid].x, found[fid].y)

    # Step 3: Fallback to shoulders if the waist is hidden
    if 5 in found and 6 in found:
        return ((found[5].x + found[6].x) / 2.0,
                (found[5].y + found[6].y) / 2.0)

    # Final Fallback: Just use the neck or nose if that's all we can see
    for fid in [17, 0]:
        if fid in found:
            return (found[fid].x, found[fid].y)

    return None

def euclidean_distance(p1, p2):
    """The classic 'Pythagorean' way to find the straight-line distance between two points[cite: 17, 25]."""
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)

def draw_hud(frame, people_count, frame_violations, frame_id, threshold):
    """Renders the top status bar and the 'All Clear' or 'Violation' message."""
    status = f"VIOLATION x{frame_violations}" if frame_violations else "ALL CLEAR"
    color  = RED if frame_violations else GREEN

    # Draw a solid black background bar at the top for readability
    cv2.rectangle(frame, (0, 0), (FRAME_WIDTH, 70), (0, 0, 0), -1)

    # Print the live count and safety status
    cv2.putText(frame,
                f"People: {people_count}   {status}",
                (10, 28),
                cv2.FONT_HERSHEY_SIMPLEX, 0.85, color, 2, cv2.LINE_AA)

    # Print the frame number and our current detection threshold
    cv2.putText(frame,
                f"Frame: {frame_id}   Threshold: {int(threshold)} px",
                (10, 55),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, WHITE, 1, cv2.LINE_AA)

# MAIN EXECUTION
def main():
    # Start the camera stream using OpenCV
    cap = cv2.VideoCapture(CAMERA_INDEX)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  FRAME_WIDTH)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, FRAME_HEIGHT)
    cap.set(cv2.CAP_PROP_FPS,          FRAME_FPS)

    # We force MJPEG format to prevent the Jetson's USB bus from getting overwhelmed
    cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*'MJPG'))

    if not cap.isOpened():
        print(f"[ERROR] Can't talk to the camera. Is it plugged into index {CAMERA_INDEX}?")
        sys.exit(1)

    # Wake up the PoseNet model (ResNet-18 is the best balance of speed/accuracy) [cite: 5]
    print("[INFO] Waking up the AI (resnet18-body)...")
    net = jetson_inference.poseNet("resnet18-body", threshold=0.15)

    print("[INFO] System ready. Press Q to exit.")

    frame_id   = 0
    violations = 0

    try:
        while True:
            # Grab a frame from the camera
            ret, frame_bgr = cap.read()
            if not ret or frame_bgr is None:
                continue

            frame_id += 1

            # The AI library needs RGBA format, but OpenCV gives us BGR. Let's swap them.
            frame_rgba = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGBA)
            cuda_img   = jetson_utils.cudaFromNumpy(frame_rgba)

            # Let the GPU do the heavy lifting: identify all human poses in the frame
            poses = net.Process(cuda_img, overlay="box,links,keypoints")

            # Bring the processed AI image back to a format OpenCV can work with
            jetson_utils.cudaDeviceSynchronize()
            frame_bgr = cv2.cvtColor(
                jetson_utils.cudaToNumpy(cuda_img), cv2.COLOR_RGBA2BGR
            )

            # Extract the 'anchor point' for every person detected [cite: 21]
            centers = []
            for pose in poses:
                center = get_hip_center(pose)
                if center:
                    centers.append(center)
                    # Draw a green dot at their center point
                    cv2.circle(frame_bgr, (int(center[0]), int(center[1])), 8, GREEN, -1)

            # Compare every person against everyone else to find distancing violations [cite: 19]
            frame_violations = 0
            for i in range(len(centers)):
                for j in range(i + 1, len(centers)):
                    dist = euclidean_distance(centers[i], centers[j])

                    # If they are too close, we light up the alert [cite: 26]
                    if dist < DISTANCE_THRESHOLD_PX:
                        frame_violations += 1
                        violations += 1

                        # Turn their center dots red and draw a line between them
                        cv2.circle(frame_bgr, (int(centers[i][0]), int(centers[i][1])), 10, RED, -1)
                        cv2.circle(frame_bgr, (int(centers[j][0]), int(centers[j][1])), 10, RED, -1)
                        cv2.line(frame_bgr,
                                 (int(centers[i][0]), int(centers[i][1])),
                                 (int(centers[j][0]), int(centers[j][1])),
                                 RED, 2, cv2.LINE_AA)

                        # Label the exact pixel distance right on the line
                        mid_x = int((centers[i][0] + centers[j][0]) / 2)
                        mid_y = int((centers[i][1] + centers[j][1]) / 2)
                        cv2.putText(frame_bgr, f"{int(dist)}px", (mid_x, mid_y),
                                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, YELLOW, 1, cv2.LINE_AA)

            # Update the on-screen dashboard
            draw_hud(frame_bgr, len(centers), frame_violations, frame_id, DISTANCE_THRESHOLD_PX)

            # Show the final results in a window [cite: 18]
            cv2.imshow("Social Distancing Detection", frame_bgr)

            # Listen for the 'Q' key to shut down safely
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

    except KeyboardInterrupt:
        print("\n[INFO] Manual stop requested.")

    finally:
        # Cleanup: release the camera and close windows
        cap.release()
        cv2.destroyAllWindows()

    print(f"\nFinal Lab Stats:")
    print(f"  Frames analyzed : {frame_id}")
    print(f"  Total violations detected: {violations}")

if __name__ == "__main__":
    main()